# Site settings
title: MusicBee Remote for Android
email: kelsos@kelsos.net
description: A remote control application that allows you to control Musicbee from your Android device.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://mbrc.kelsos.net/" # the base hostname & protocol for your site

collections:
  - help

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: ""
data-ad-client: ""
google_ad_client: ""

google_analytics: "UA-34909088-2"
addthis_id: "ra-585a6a447a078e7c"
disqus_account: "http-kelsos-net"

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: envelope
    url: mailto:kelsos@kelsos.net
  - title: twitter
    url: https://twitter.com/MusicBeeRemote
  - title: facebook
    url: https://facebook.com/MusicbeeRemote
  - title: google-plus
    url: https://plus.google.com/106603781998988521234
  - title: github
    url: https://github.com/kelsos/mbrc
  - title: github
    url: https://github.com/kelsos/mbrc-plugin


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
repository: kelsos.github.io/mbrc

