[versions]
accompanist = "0.34.0"
activityCompose = "1.9.0"
androidx-annotation = "1.8.0"
androidx-appcompat = "1.7.0"
androidx-arch-core-testing = "2.2.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-datastore = "1.1.1"
androidx-fragment = "1.8.1"
androidx-lifecycle = "2.8.3"
androidx-media = "1.7.0"
androidx-navigation = "2.7.7"
androidx-paging-compose = "3.3.0"
androidx-paging-runtime-ktx = "3.3.0"
androidx-preference-ktx = "1.2.1"
androidx-recyclerview = "1.3.2"
androidx-room = "2.6.1"
androidx-swiperefresh = "1.1.0"
androidx-test-core = "1.6.1"
androidx-test-espresso = "3.6.1"
androidx-test-junit = "1.2.1"
androidx-test-runner = "1.6.1"
androidx-test-truth = "1.6.0"
androidx-viewpager2 = "1.1.0"
androidx-work = "2.9.0"
arrow = "1.2.4"
cash-app-turbine = "1.1.0"
coil = "2.6.0"
compose = "1.6.8"
composeCompiler = "1.5.14"
composeUiTooling = "1.6.8"
desugar = "2.0.4"
firebaseBom = "33.1.1"
google-material = "1.12.0"
gradlePlugin-agp = "8.5.1"
gradlePlugin-crashlytics = "3.0.2"
gradlePlugin-detekt = "1.23.6"
gradlePlugin-firebasePerf = "1.4.2"
gradlePlugin-gms = "4.4.2"
gradlePlugin-kotlinter = "4.4.0"
gradlePlugin-kover = "0.8.2"
gradlePlugin-ksp = "2.0.0-1.0.22"
gradlePlugin-protobuf = "0.9.4"
gradlePlugin-versionCatalog = "0.8.4"
gradlePlugin-versionsBenManes = "0.51.0"
koin = "3.5.6"
kotlin = "2.0.0"
kotlinCoroutines = "1.8.1"
lifecycleViewmodelCompose = "2.8.3"
mockk = "1.13.11"
navigationCompose = "2.7.7"
protobuf = "4.26.1"
robolectric = "4.12.2"
squareup-leakcanary = "2.14"
squareup-moshi = "1.15.1"
squareup-okio = "3.9.0"
timber = "5.0.1"

[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core-testing" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-media = { module = "androidx.media:media", version.ref = "androidx-media" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging-compose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging-runtime-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefresh" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-truth" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
cash-app-turbine = { module = "app.cash.turbine:turbine", version.ref = "cash-app-turbine" }
coilKt-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coilKt-coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
com-android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
google-accompanistFlowLayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
google-accompanistPager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
google-accompanistPagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
google-accompanistPlaceholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
google-accompanistSwipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
google-accompanistSystemUIController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-perf-ktx = { module = "com.google.firebase:firebase-perf-ktx" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "squareup-moshi" }
squareup-moshi-lib = { module = "com.squareup.moshi:moshi", version.ref = "squareup-moshi" }
squareup-okio = { module = "com.squareup.okio:okio", version.ref = "squareup-okio" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
androidx-compose = [
    "androidx-compose-compiler",
    "androidx-compose-foundation",
    "androidx-compose-material",
    "androidx-compose-materialIconsExtended",
    "androidx-compose-runtimeLivedata",
    "androidx-compose-ui",
    "androidx-compose-uiTooling",
    "androidx-paging-compose",
]
androidx-lifecycle = [
    "androidx-lifecycle-common",
    "androidx-lifecycle-lifecycleViewmodelCompose",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
]
androidx-navigation = [
    "androidx-navigation-fragment-ktx",
    "androidx-navigation-navigationCompose",
    "androidx-navigation-ui-ktx",
]
androidx-room = [
    "androidx-room-ktx",
    "androidx-room-paging",
    "androidx-room-runtime",
]
androidx-test-espresso = [
    "androidx-test-espresso-contrib",
    "androidx-test-espresso-core",
    "androidx-test-espresso-intents",
]
coil = [
    "coilKt-coil",
    "coilKt-coilCompose",
]
coroutines = [
    "kotlin-coroutines-android",
    "kotlin-coroutines-core",
]
google-accompanist = [
    "google-accompanistFlowLayout",
    "google-accompanistPager",
    "google-accompanistPagerIndicators",
    "google-accompanistPlaceholder",
    "google-accompanistSwipeRefresh",
    "google-accompanistSystemUIController",
]
google-firebase = [
    "google-firebase-analytics-ktx",
    "google-firebase-crashlytics-ktx",
    "google-firebase-perf-ktx",
]
koin = [
    "koin-android",
    "koin-compose",
    "koin-workmanager",
]
arrow = [
    "arrow-core",
    "arrow-fx-coroutines",
    "arrow-resilience"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin-agp" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin-agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "gradlePlugin-crashlytics" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "gradlePlugin-detekt" }
detektFormatting = { id = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "gradlePlugin-detekt" }
firebasePerf = { id = "com.google.firebase.firebase-perf", version.ref = "gradlePlugin-firebasePerf" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gradlePlugin-gms" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradlePlugin-kotlinter" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "gradlePlugin-kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "gradlePlugin-ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "gradlePlugin-protobuf" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradlePlugin-versionCatalog" }
versionsBenManes = { id = "com.github.ben-manes.versions", version.ref = "gradlePlugin-versionsBenManes" }
